server:
  # 配置端口
  port: 8083
spring:
  application:
    name: 'candy-rebate-web'
  ## 数据库访问配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-8vbyrdzy1e74921c0do.mysql.zhangbei.rds.aliyuncs.com:3306/candy_project_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: zhu_rds
    password: '!QAZxsw2kwz'
    # 使用druid数据源
    druid:
      #最大连接池数量
      max-active: 50
      #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initial-size: 1
      min-idle: 1
      # 配置获取连接等待超时的时间
      max-wait: 10000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: false
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: 20
      #和上面的等价
      max-open-prepared-statements: 20
      #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      validation-query: select 'x'
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
  redis:
    host: 121.89.195.134
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    password: "!QAZxsw2kwz"



  #邮箱配置
  mail:
    host: smtp.126.com
    username: FatMaJin_Buu@126.com
    password: ZFNGUITDXBYJLKWF
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallbock: false
    port: 465

  profiles:
    active: 'dev'
  # freemarker模板引擎
  freemarker:
    allow-request-override: true
    allow-session-override: true
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html;
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    template-loader-path: classpath:/email/,classpath:/templates/,classpath:/public/
    prefix:
    suffix: .ftl
    request-context-attribute: request
    settings:
      template_update_delay: 0
      url_escaping_charset: UTF-8
      locale: UTF-8
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      template_exception_handler: html_debug
      # 数字格式化，无小数点
      number_format: '0.#'
      # 设置freemarker标签 0,1,2 0=自动识别，默认1
      tag_syntax: 'auto_detect'

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.com.mjb.candyrebateadmin.module.domain
