spring:
  #邮箱配置
  mail:
    host: "smtp.126.com"
    username: "FatMaJin_Buu@126.com"
    password: ZFNGUITDXBYJLKWF
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true